export const userPhotosConstants = {
    GET_PHOTOS_REQUEST: 'GET_PHOTOS_REQUEST',
    GET_PHOTOS_SUCCESS: 'GET_PHOTOS_SUCCESS',
    GET_PHOTOS_FAILURE: 'GET_PHOTOS_FAILURE',
};
export const deleteUserPhotoConstants = {
    DELETE_PHOTO_REQUEST: 'DELETE_PHOTO_REQUEST',
    DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
    DELETE_PHOTO_FAILURE: 'DELETE_PHOTO_FAILURE',
};
