export const userConstants = {
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
};
export const addUserConstants = {
    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE: 'ADD_USER_FAILURE',
};
export const changeAuthUser = {
    CHANGE_AUTH_USER_REQUEST: 'CHANGE_AUTH_USER_REQUEST',
    CHANGE_AUTH_USER_SUCCESS: 'CHANGE_AUTH_USER_SUCCESS',
    CHANGE_AUTH_USER_FAILURE: 'CHANGE_AUTH_USER_FAILURE',
};