export const userPostsConstants = {
    GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
    ADD_POST_REQUEST:  'ADD_POST_REQUEST',
    ADD_POST_SUCCESS:  'ADD_POST_SUCCESS',
    ADD_POST_FAILURE:  'ADD_POST_FAILURE',
};
