export const userConstants = {
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
};
export const userPostsConstants = {
    GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
};
export const userCommentsConstants = {
    GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',
};
export const userAlbumsConstants = {
    GET_ALBUMS_REQUEST: 'GET_ALBUMS_REQUEST',
    GET_ALBUMS_SUCCESS: 'GET_ALBUMS_SUCCESS',
    GET_ALBUMS_FAILURE: 'GET_ALBUMS_FAILURE',
};
export const userPhotosConstants = {
    GET_PHOTOS_REQUEST: 'GET_PHOTOS_REQUEST',
    GET_PHOTOS_SUCCESS: 'GET_PHOTOS_SUCCESS',
    GET_PHOTOS_FAILURE: 'GET_PHOTOS_FAILURE',
};
export const deleteUserPhotoConstants = {
    DELETE_PHOTO_REQUEST: 'DELETE_PHOTO_REQUEST',
    DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
    DELETE_PHOTO_FAILURE: 'DELETE_PHOTO_FAILURE',
};
export const deleteCommentConstants = {
    DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',
};
export const  editCommentsConstans = {
    EDIT_COMMENT_REQUEST: 'EDIT_COMMENT_REQUEST',
    EDIT_COMMENT_SUCCESS: 'EDIT_COMMENT_SUCCESS',
    EDIT_COMMENT_FAILURE: 'EDIT_COMMENT_FAILURE',
};
export const  addCommentsConstants = {
    ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
};